# Generated by Django 3.0.7 on 2020-11-02 14:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0020_auto_20201102_1354'),
    ]

    operations = [
        migrations.RenameField(
            model_name='clothesset',
            old_name='name',
            new_name='alias',
        ),
        migrations.RenameField(
            model_name='user',
            old_name='username',
            new_name='user_id',
        ),
        migrations.RenameField(
            model_name='user',
            old_name='nickname',
            new_name='user_name',
        ),
    ]
