# Generated by Django 3.0.7 on 2020-11-04 15:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0022_auto_20201102_1415'),
    ]

    operations = [
        migrations.CreateModel(
            name='CategoryData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')), 
                ('clothes_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.Clothes')),
                ('upper_category', models.CharField(choices=[('하의', '하의'), ('원피스', '원피스'), ('아우터', '아우터'), ('치마', '치마'), ('상의', '상의')], max_length=9)),
                ('lower_category', models.CharField(choices=[('반팔티셔츠', '반팔티셔츠'), ('긴팔티셔츠', '긴팔티셔츠'), ('반팔셔츠', '반팔셔츠'), ('긴팔셔츠', '긴팔셔츠'), ('맨투맨', '맨투맨'), ('터틀넥', '터틀넥'), ('후드티', '후드티'), ('니트', '니트'), ('블라우스', '블라우스'), ('끈나시', '끈나시'), ('민소매', '민소매'), ('반바지', '반바지'), ('핫팬츠', '핫팬츠'), ('슬랙스', '슬랙스'), ('청바지', '청바지'), ('골덴바지', '골덴바지'), ('트레이닝바지', '트레이닝바지'), ('미니스커트', '미니스커트'), ('롱스커트', '롱스커트'), ('블레이져', '블레이져'), ('숏패딩', '숏패딩'), ('조끼패딩', '조끼패딩'), ('롱패딩', '롱패딩'), ('야구점퍼', '야구점퍼'), ('항공점퍼', '항공점퍼'), ('바람막이', '바람막이'), ('야상', '야상'), ('무스탕', '무스탕'), ('코트', '코트'), ('트랙탑', '트랙탑'), ('가죽자켓', '가죽자켓'), ('청자켓', '청자켓'), ('가디건', '가디건'), ('원피스', '원피스')], max_length=18)),
            ],
        ),
    ]
