# Generated by Django 3.0.7 on 2020-11-11 16:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0023_categorydata'),
    ]

    operations = [
        migrations.RenameField(
            model_name='categorydata',
            old_name='clothes_id',
            new_name='clothes',
        ),
    ]
