# Generated by Django 3.0.7 on 2020-11-11 16:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0024_auto_20201111_1634'),
    ]

    operations = [
        migrations.AddField(
            model_name='clothes',
            name='category',
            field=models.CharField(max_length=30, null=True),
        ),
    ]
