# Generated by Django 3.0.7 on 2020-11-11 19:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0027_auto_20201111_1910'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='clothes',
            name='categories',
        ),
        migrations.AddField(
            model_name='clothes',
            name='category_num',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='api.CategoryData'),
        ),
    ]
