# Generated by Django 3.0.7 on 2020-11-11 19:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0028_auto_20201111_1927'),
    ]

    operations = [
        migrations.RenameField(
            model_name='clothes',
            old_name='category_num',
            new_name='category',
        ),
    ]
