# Generated by Django 3.0.7 on 2020-12-03 23:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0029_auto_20201111_1942'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='clothes',
            name='lower_category',
        ),
        migrations.RemoveField(
            model_name='clothes',
            name='upper_category',
        ),
    ]
